### PR TITLE
trading card overhaul

### PR DESCRIPTION
**Pull request by Dragoninja54**

### CODE REVIEW

**Comment by Dragoninja54** [comment]
If anyone knows a good way to test these things please tell me because as of right now i'm just loading up a world and looking through a dungeon manually lmao

**Comment by Dragoninja54** [comment]
I have literally no idea if any of this actually looks good i'm just writing stuff down and praying

**Comment by Dragoninja54** [comment]
I have an idea to actually test out these cards but i'm not sure if it'll work

**Comment by Dragoninja54** [comment]
it worked

**Comment by Dragoninja54** [comment]
its still really dumb and inefficient but it works better than what i was doing

**Review by fnar — COMMENTED** [review]
Thanks for this, so much. Seriously.

**Pull request merged**
